game_directory := "C:\Program Files (x86)\Steam\steamapps\common\Granblue Fantasy Versus Rising\RED\Binaries\Win64"
output_directory := A_WorkingDir "\automation_output"

key_move_left := "A"
key_move_right := "D"
key_move_down := "S"
key_jump := "Space"

key_skill := "Del"
key_light := "Ins"
key_medium := "Home"
key_heavy := "PgUp"
key_unique := "PgDn"
key_throw := "End"
key_block := "Left"