game_directory := "C:\Program Files (x86)\Steam\steamapps\common\Granblue Fantasy Versus Rising\RED\Binaries\Win64"
output_directory := A_WorkingDir "\automation_output"

key_move_left := "A"
key_move_right := "D"
key_move_down := "S"
key_jump := "W"

key_skill := "P"
key_light := "U"
key_medium := "I"
key_heavy := "K"
key_unique := "J"
key_throw := "O"
key_block := ";"
