name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}
      - name: Setup github SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.GBVSR_FRAME_METER_SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
      - name: Setup Visual Studio Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
      - name: Run Tests
        run: .\scripts\test.ps1

  build:
    name: Build Release
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}
      - name: Setup github SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.GBVSR_FRAME_METER_SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
      - name: Setup Visual Studio Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
      - name: Generate solution
        run: .\scripts\generate_solution.ps1
      - name: Compile & Package
        run: .\scripts\release.ps1
