name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}
      - name: Setup github SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.GBVSR_FRAME_METER_SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
      - name: Setup Visual Studio Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
      - name: Generate solution
        run: cmake -S . -B output
      - name: Build binaries
        run: MSBuild.exe .\output\MyMods.sln /p:Configuration=Game__Shipping__Win64
