name: Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}
      - name: Setup github SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.GBVSR_FRAME_METER_SSH_PRIVATE_KEY }}
      - name: Prepare release
        run: .\scripts\release.ps1
      - name: Bump version
        id: tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: major
      - name: Make Github release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ steps.tag.outputs.new_tag }}"
          files: gbvsr-frame-meter.zip
          fail_on_unmatched_files: true
