name: Release

on:
  workflow_dispatch:
    inputs:
      version_number:
        type: string
        required: true
        description: "User-facing version number with no prefix"

jobs:
  build:
    name: Build
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}
      - name: Setup github SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.GBVSR_FRAME_METER_SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
      - name: Setup Visual Studio Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: "2.9.3"
      - name: Compile & Package
        run: .\scripts\release.ps1
      - name: Make Github release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ inputs.version_number }}"
          files: gbvsr-frame-meter.zip
          fail_on_unmatched_files: true
